name: Update Torrent Blocklist

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC (optional)
  push:
    branches:
      - main

jobs:
  update-torrent-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Fetch torrent blocklist
      run: |
        # Download the list of trackers from the Pi-hole repository
        curl -o torrent-trackers.txt https://raw.githubusercontent.com/SM443/Pi-hole-Torrent-Blocklist/main/all-torrent-trackres.txt

    - name: Convert to OpenClash format
      run: |
        # Create an empty file to store the formatted list
        echo "# Formatted Torrent List" > formatted-torrent-list.yaml

        # Loop through each line of the torrent-trackers.txt and format it
        while IFS= read -r line; do
          # Skip empty lines or lines starting with a number or a comment
          if [[ ! "$line" =~ ^# && -n "$line" ]]; then
            # Add '+' to the domain and append it to the formatted file
            echo "+.$line" >> formatted-torrent-list.yaml
          fi
        done < torrent-trackers.txt

    - name: Update tr-site.yaml
      run: |
        # Assuming the OpenClash YAML file is 'tr-site.yaml'
        # Append the formatted list to your OpenClash YAML configuration file
        cat formatted-torrent-list.yaml >> tr-site.yaml

     - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automatic update Rule Provider Clash'
          commit_author: 'GitHub Actions <github-actions@users.noreply.github.com>'
          branch: 'main'  # Ensure the correct branch is specified (use 'main' or 'master')
          token: ${{ secrets.GH-Token }}  # Use the token from secrets
