name: Rule Provider

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas tldextract pyyaml openpyxl

      - name: Download and process source lists
        #working-directory: ./rule_provider
        run: |
          echo "Downloading Pi-hole Torrent Blocklist..."
          curl -sSf -o pi-hole-torrent.txt https://raw.githubusercontent.com/SM443/Pi-hole-Torrent-Blocklist/main/all-torrent-trackers.txt
          
          # Processing the torrent tracker list
          python3 - <<EOF
          import re
          import yaml

          with open("pi-hole-torrent.txt", "r") as file:
              input_text = file.read()

          payload_lines = re.findall(r"^([a-zA-Z0-9.-]+)", input_text)
          payload = [f'"+.{line}"' for line in payload_lines]

          data = {
              "payload": payload
          }

          yaml_output = yaml.dump(data, sort_keys=False, default_flow_style=False)

          formatted_yaml = re.sub(r"(\s+-) '(.+)'", r"\1 \2", yaml_output)

          with open("tr-site.yaml", "w") as file:
              file.write(formatted_yaml)
          EOF

          rm pi-hole-torrent.txt

      - name: Commit changes to the repository
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update tr-site.yaml with the latest torrent blocklist'
          author_name: 'GitHub Action'
          author_email: 'github-actions@users.noreply.github.com'
          add: 'tr-site.yaml'
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Push changes to the repository
        run: git push
